### ISSUE TITLE
What slideshow software are you using?

### ISSUE THREAD

**Issue by josegonzalez** [ryuzee/open-slideshare#59]
I looked at your source, and there are references to [BxSlider](http://bxslider.com/) but it doesn't look like that in your ui.

I'm currently using [slick.js](https://github.com/shashankmehta/slick.js) for a similar project, hence the question.

**Comment by ryuzee** [comment]
@josegonzalez This app uses BxSlider. See https://github.com/ryuzee/open-slideshare/blob/master/app/View/Elements/slide.ctp

**Comment by josegonzalez** [comment]
Oh sorry, how are you handling the embed codes?

**Comment by ryuzee** [comment]
I would like to clarify your question. If your question means how to manage or implements embedded player that will be embedded in other web site, you'd better see embedded method in SlidesController.
/slides/embedded/N returns JavaScript.

If the answer above is not one you expected, please let me know.

**Comment by josegonzalez** [comment]
Found it, that answers my questions. Thanks!
